# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Electronica y Ciencia
email: electronicayciencia@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog técnico sobre proyectos caseros de electrónica, informática y física.
baseurl: "/pruebas-blog" # the subpath of your site, e.g. /blog
url: "https://electronicayciencia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: electronicaycie
github_username:  electronicayciencia
permalink: /:categories/:year/:month/:title:output_ext

show_excerpts: true

# Build settings
markdown: kramdown
theme: minima

minima:
  date_format: "%-d %b %Y"

disqus:
    shortname: electronicayciencia

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
