# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Pruebas Electronica y Ciencia
email: electronicayciencia@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog técnico sobre proyectos caseros de electrónica, informática y física.
baseurl: "/pruebas-blog" # the subpath of your site, e.g. /blog
url: "https://electronicayciencia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:title:output_ext

show_excerpts: true

logo: "/assets/logo_eyc.png"

# Build settings
markdown: kramdown

theme: minima


disqus:
    shortname: electronicayciencia

google_analytics: UA-15570327-6

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

twitter_username: electronicaycie
github_username:  electronicayciencia
linkedin_username: reinosoguzman

minima:
  date_format: "%-d %b %Y"
  social_links:
    twitter: electronicaycie
    github: electronicayciencia
    linkedin: reinosoguzman

paginate: 4

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
